### ISSUE TITLE
Is there a c/c++ client for nats-streaming?

### ISSUE THREAD

**Issue by nellson** [nats-io/go-nats-streaming#102]

**Comment by aricart** [comment]
Not yet!

**Comment by kozlovic** [comment]
@nellson Thank you for your interest. Unfortunately, there is no C/C++ client for NATS Streaming at this time, as we have other priorities. Is this something that you would need in the short term, or just curious about it?

**Comment by nellson** [comment]
@kozlovic Thank you for your reply.  I am a senior engineer in Tencent, and looking for a message queue for Tecent Game. I have tested Kafka\RabbitMQ\Nats and Nats Streaming, and really impressed by the Nats's performance. And Nats is really easy to use and deploy. 

However we need a message queue with persistence, so I choose Nats Streaming, but we mainly develop use c/c++. So I have to only two choice: 1. Fork NATS and add persistence. 2 Wait for Nats Streaming C Client, but the question is when there will be? Could you give me more information?

**Comment by kozlovic** [comment]
@nellson Our community manager Brian Flannery will jump in to discuss your requirements in more details. Thanks.

**Comment by nellson** [comment]
@bjflanne @kozlovic  Thanks a lot! I will send a email to bjflanne to set up a time.

**Comment by Jamby93** [comment]
Got the same question, I'm about in the same situation of @nellson. Would you mind share the private discussion's result in order to help who find this thread searching on google?
Thanks

**Comment by arifsetiawan** [comment]
We also interested on this. Is there any news you guys can share?

**Comment by ColinSullivan1** [comment]
Reopening this issue; this is gaining momentum.

One option we'd like to explore is using the `-buildmode` flag.  This may be best as wrapper functions in a new package over `go-nats-streaming` so the exports are C-friendly and to work around the main package requirement, but experimentation is needed.

```
-buildmode=c-shared
	Build the listed main package, plus all packages it imports,
	into a C shared library. The only callable symbols will
	be those functions exported using a cgo //export comment.
	Requires exactly one main package to be listed.
```

A great writeup of how this works can be found [here](
https://medium.com/learning-the-go-programming-language/calling-go-functions-from-other-languages-4c7d8bcc69bf), with a corresponding [repository](https://github.com/vladimirvivien/go-cshared-examples).

There are still a multitude of unanswered questions here (e.g. what about handling structures?), but I'd like to open this up to the community for comments or offers to contribute.

**Comment by fro0m** [comment]
there is a great need in cxx realization

**Comment by santiGoncalves** [comment]
will there be any cnats streaming? we are at the moment to choose between rabbitmq kafka and nats, we love nats but the streaming is a must for us, is there a timeline for this? or is not planned at all? we can start with nats and move to nats streaming later if its on the roadmap thanks

**Comment by fmvin** [comment]
Is there any movement on this issue? We are very interesting in the streaming c or c++98 client. Unfortunatly we cannot use kafka due to very old-fashioned Linux distro in our production but NATS works very well on it.

**Comment by cpowersrbr** [comment]
We are also keen on a C/C++ streaming client. Is there any hint on when one might be available?

**Comment by kozlovic** [comment]
@nellson @arifsetiawan @fro0m @santiGoncalves @fmvin @cpowersrbr I understand that you may no longer have interest on that, but if you do, check the PR for NATS C Streaming [here](https://github.com/nats-io/cnats/pull/157).

Also, I am closing this issue and you can follow/comment on the one in the NATS C client repo: https://github.com/nats-io/cnats/issues/140.

Thanks!

**Comment by kozlovic** [comment]
Just released today as beta release (https://github.com/nats-io/cnats/releases/tag/v1.8.0-beta). If feedback regarding API is ok (or no feedback), then we will get out of beta status. Thanks for your patience and interest in the C client!

**Comment by kozlovic** [comment]
Wondering if people interested in the NATS Streaming C Client had a chance to evaluate the 1.8.0-beta release. If so, did you find any API design issue that should be addressed before getting out of beta status? If no answer, I may release 1.8.0 this week. Thanks!

**Comment by vbrunko-voc** [comment]
> Wondering if people interested in the NATS Streaming C Client had a chance to evaluate the 1.8.0-beta release. If so, did you find any API design issue that should be addressed before getting out of beta status? If no answer, I may release 1.8.0 this week. Thanks!

I would be interested for this option to be in: Change ClientName (Connection Name) when connecting to JS using NATS from CPP

**Comment by kozlovic** [comment]
@vbrunko-voc It sounds like you are asking about the C client instead of Go client. Regardless, could you elaborate on this? "I would be interested for this option to be in: Change ClientName (Connection Name) when connecting to JS using NATS from CPP". Note that NATS Streaming is deprecated and new features are unlikely to be implemented.

**Comment by vbrunko-voc** [comment]
@kozlovic yes sure. The basic idea is that our c-clients written in NATS show up in Grafana/Prometheus as UUIDs. Have no idea what else to change in our source code to give them names in analogy to Go driver e.g.

**Comment by kozlovic** [comment]
@vbrunko-voc Unfortunately the C client sets the NATS Connection Name to what the provided "client ID" is (in the natsStan_Connect() call). Unless you change your client IDs to have a more meaningful name (maybe as the prefix of your UUIDs), we would need to add a new option to be able to set the NATS connection name. Given that the NATS Streaming project is close to its EOL, not sure if that makes sense. Still, it could be a small addition, low impact, that would be possible to make. First let me know if the workaround described above would work or not. If not, please create an issue in the NATS C client repo so we can track the enhancement request (https://github.com/nats-io/nats.c)

**Comment by vbrunko-voc** [comment]
Got it, thanks @kozlovic , we'll try the other ways.
So, instead of NATS Streaming, what do we left with? JetStream?
