### ISSUE TITLE
Reconnection when Server Reboot

### ISSUE THREAD

**Issue by diegofernandes** [nats-io/go-nats-streaming#106]
We I restart the server the pub and sub stop to send and receive data. I have try to handler close connection but without success.

**Comment by kozlovic** [comment]
You need to make sure that the server is using file stores, otherwise no state is persisted, and so on restart, it looks like nothing happens on your client side.

**Comment by kozlovic** [comment]
To run with file stores: `-store file -dir <data store directory>`

**Comment by diegofernandes** [comment]
this happens on pub too. Is It because of memory store?

**Comment by kozlovic** [comment]
Yes, it matters for pub too. The server subscribes to specific subjects to communicate with its clients. After a restart without persistent state, new subjects are being used, so the communication between the restarted server and old clients is not happening (even though there is NATS connectivity between the server and clients).
