### ISSUE TITLE
Add Subscription.Close() to close a durable without removing durable interest

### ISSUE THREAD

**Issue by kozlovic** [nats-io/go-nats-streaming#114]
A durable (including durable queue subscriber) would be removed from the server - so delivery to this subscriber would stop - without removing the durable interest, that is, durable subscription can be resumed.

A summary:
### Unsubscribe()
- For a durable, `Unsubscribe()` removes the durable subscription. A restart with same durable name is a new one and can receive old messages.
- For a durable queue group, the last member calling `Unsubscribe()` removes the durable queue group.
### Close()
- For a durable (including any durable queue member in a group) `Close()` stops delivery to this subscriber but does not remove the durable subscription (the durable queue group is not removed by the last member calling `Close()`).
- For a durable (including durable queue subscribers), calling `Close()` when connecting to a server that does not offer this feature causes the API to return the error `ErrNoServerSupport`.
- For non durables, `Close()` is equivalent to `Unsubscribe()`, so no error is returned even if connecting to an older server.

**Comment by sfrooster** [comment]
Will this be reviewed / merged soon?

**Comment by kozlovic** [comment]
I am a bit wary about adding the protocol version this way. It would not solve the issue of having a server say v0.3.1 start, a client "connects" and get server protocol version that says it can do Close(), then server stops and restarted as v0.2.2 and the Close() becomes an Unsubscribe(). I am wondering if for this feature I should not fallback to add a new subscribe in the server for the subscription close, add a new SubscriptionCloseRequest to prevent the above issue. A client sending a Close() to an old server would timeout though. What do you think?

**Comment by sfrooster** [comment]
So it would be adding a different type of subscribe type - so subscribing with protocol version 0.3.1 vs 0.2.2 - and adding subscription close to 0.3.1.  And then in your above scenario, the client needs to make sure it's checking the protocol version on connect and doing the appropriate action at disconnect based on that (either close or unsubscribe).

So, the change is as follows (for QG)?
OLD
- close, does not exist
- unsub, disconnect, if last QG subscriber remove QG
NEW
- close, disconnect
- unsub, disconnect, if last QG subscriber remove QG

Why can't calling close on an old server just throw a not supported exception?

**Comment by kozlovic** [comment]
I was saying that the protocol version is not helping because of the disconnected nature of STAN clients. So I was saying that I would NOT add the protocol version. Server/Client would have a new protocol for subscription close. It means that new client trying to send subscription close protocol to old server would time-out since old server would not be listening for this type of protocol.

**Comment by kozlovic** [comment]
When a server stops/restart, a client does not know. They are not directly connected to each other. So having the protocol version in the initial client's connect() request/reply does not help when servers are stopped/restarted while clients are still running.

**Comment by sfrooster** [comment]
So making a sub close protocol call to an old server, the server will do nothing and what will the client experience? Nothing? Or... ?

**Comment by kozlovic** [comment]
.. a timeout since the Close() is a request/reply with a server. Since old server is not listening on special subject where this protocol would be receive from, the client will experience a timeout. Not ideal, but again just wary about introducing a protocol version if this is not helping in case of server restarts (from new to old).

**Comment by sfrooster** [comment]
Is the client able to trap that situation? If so, then it could trap and instead issue and unsubscribe or just ignore.

**Comment by kozlovic** [comment]
However, if users are fine with the issue of restarting with older server, then the current approach would probably be best. I could even make the ProtocolVersion a client method (on top of rejecting Close() if server protocol version is older). In the future, I could make sure that servers will persist their protocol version and refuse to restart if protocol is newer than what they are, but that would not solve the problem between 0.3.0 and older.

**Comment by sfrooster** [comment]
There's no reason for anyone to be using the older server, especially not with a newer client.  I would do the right thing without significant concern for older servers and then add a note to the readme about the issue with using an older server.
