### ISSUE TITLE
Data race on publish?

### ISSUE THREAD

**Issue by olivere** [nats-io/go-nats-streaming#129]
We're evaluating NATS Streaming Server for the PubSub system in a microservices architecture. We currently use it only for simple "fire-and-forget" messaging such as progress notifications.

While using that, we found that the number of goroutines in go-nats-streaming seems to be ever increasing. This is what we get after running the web server part for a while. It seems that the goroutines are stuck in [`stan.go:402`](https://github.com/nats-io/go-nats-streaming/blob/master/stan.go#L402).

```
goroutine profile: total 168
69 @ 0x3f20d 0x3f2fe 0x13b08 0x1380d 0x58d855 0x72111
#	0x58d854	github.com/meplato/cloud/vendor/github.com/nats-io/go-nats-streaming.(*conn).publishAsync.func1+0x144	/Users/oliver/gocode/src/github.com/meplato/cloud/vendor/github.com/nats-io/go-nats-streaming/stan.go:402

8 @ 0x3f20d 0x50133 0x4eddc 0x25167e 0x72111
#	0x25167d	github.com/meplato/cloud/vendor/google.golang.org/grpc.newClientStream.func2+0x54d	/Users/oliver/gocode/src/github.com/meplato/cloud/vendor/google.golang.org/grpc/stream.go:204
```

After a while, this number exceeds the number of goroutines that the race detector considers to be a problem (`race: limit on 8192 simultaneously alive goroutines is exceeded, dying`).

```
goroutine profile: total 1141
1042 @ 0x3f20d 0x3f2fe 0x13b08 0x1380d 0x58d855 0x72111
#	0x58d854	github.com/meplato/cloud/vendor/github.com/nats-io/go-nats-streaming.(*conn).publishAsync.func1+0x144	/Users/oliver/gocode/src/github.com/meplato/cloud/vendor/github.com/nats-io/go-nats-streaming/stan.go:402

8 @ 0x3f20d 0x50133 0x4eddc 0x25167e 0x72111
#	0x25167d	github.com/meplato/cloud/vendor/google.golang.org/grpc.newClientStream.func2+0x54d	/Users/oliver/gocode/src/github.com/meplato/cloud/vendor/google.golang.org/grpc/stream.go:204
```

Here's how we publish messages:

```
// PublishJSON publishes a message serialized as JSON.
// Strings, pointers to strings, and byte arrays get sent as-is,
// all other objects are serialized as JSON.
func (b *natsBroker) PublishJSON(ctx context.Context, topic string, msg interface{}) error {
	switch msg := msg.(type) {
	case string:
		return b.conn.Publish(topic, []byte(msg))
	case *string:
		if msg == nil {
			return b.conn.Publish(topic, nil)
		}
		return b.conn.Publish(topic, []byte(*msg))
	case []byte:
		return b.conn.Publish(topic, msg)
	}

	// Fallback to JSON encoding
	data, err := json.Marshal(msg)
	if err != nil {
		return err
	}
	return b.conn.Publish(topic, data)
}

...

// Publish progress
sch.broker.PublishJSON(context.Background(), sync.ProgressTopic, sync.ProgressEvent{
	Current:    int(current),
	Total:      int(total),
	ETA:        eta.Unix(),
})
```

We're using the current version of NATS streaming server from the GitHub repository:

```
[52172] 2016/12/29 12:30:02.190442 [INF] Starting nats-streaming-server[cloud-nats] version 0.3.7
[52172] 2016/12/29 12:30:02.190681 [INF] Starting nats-server version 0.9.6
[52172] 2016/12/29 12:30:02.190712 [INF] Listening for client connections on 0.0.0.0:4222
[52172] 2016/12/29 12:30:02.190806 [INF] Server is ready
[52172] 2016/12/29 12:30:02.469346 [INF] STAN: Message store is MEMORY
[52172] 2016/12/29 12:30:02.469358 [INF] STAN: --------- Store Limits ---------
[52172] 2016/12/29 12:30:02.469362 [INF] STAN: Channels:                  100 *
[52172] 2016/12/29 12:30:02.469369 [INF] STAN: -------- channels limits -------
[52172] 2016/12/29 12:30:02.469372 [INF] STAN:   Subscriptions:          1000 *
[52172] 2016/12/29 12:30:02.469376 [INF] STAN:   Messages     :       1000000 *
[52172] 2016/12/29 12:30:02.469397 [INF] STAN:   Bytes        :     976.56 MB *
[52172] 2016/12/29 12:30:02.469399 [INF] STAN:   Age          :     unlimited *
[52172] 2016/12/29 12:30:02.469400 [INF] STAN: --------------------------------
```

Of course, this could as well be a problem on our side. Can you give us a hint on how to debug this problem?

**Comment by olivere** [comment]
BTW I found that it only happens if we publish a large number of notifications, e.g. in the progress case. If we throttle the Publish call for progress messages, the problem does not occur.

**Comment by kozlovic** [comment]
@olivere Are you sure you are not creating many go routines to publish? The `Publish()` call is not creating any go routine. The connection has one go routine to read data from server. When it receives the publish ack message, it will notify the `Publish()` call of the success or failure. So my guess is that either you are using many different connections or many go routines to do Publish() in parallel. 

I have 2 comments:
- If the progress does not need to be persisted, Streaming may not be the best approach, instead core NATS would be better.
- Unless you need direct feedback of publish error, you could refactor to use async publisher (that would not block) and provide a `AckHandler` to process possible publish errors. That may not be easy if the rest of your application is not designed to handle asynchronous errors.

**Comment by olivere** [comment]
Thanks for your time.

First of all, we want to keep it simple and use NATS Streaming Server for both fire-and-forget messaging like in the case described above (via `Subscribe`) as well as queuing tasks for e.g. sharing work among a pool of distributed workers (via `QueueSubscribe`). Isn't NATS Streaming Server a feasible option for this scenario?

Second, you're right in that the problem only occurs with a `Publish` call in the progress step. That's interesting and definitely worth observing. The `Publish` call in the progress step is inside a goroutine orchestrated via [`golang.org/x/sync/errgroup`](https://godoc.org/golang.org/x/sync/errgroup#Group.Go). I will find out if that causes the problem. What's interesting is that the problem no longer occurs when I start throttling the call to Publish (which is a good idea anyway).

I'll close this for now because I agree that it seems to be a problem in our code base. Thank you.

**Comment by kozlovic** [comment]
NATS Streaming uses a message log for each channel (aka subject). Messages are removed from the log only based on the channel limits (default is 1,000,000 messages or 1,000,000 * 1024 bytes per channel). If you do not care about replaying those messages, it seems to be that it is going to consume resources for nothing.
You could always mix NATS and NATS Streaming (actually, NATS Streaming even give you access to the NATS connection that it uses internally, so you could do NATS messaging that by-pass the streaming server). However, note that NATS clients cannot communicate with NATS Streaming clients, even on the same subject. 

As for the use of `Publish`. I am not saying that there is a problem on your side, just that it looks like your framework ends-up making all these `Publish` call in parallel, therefore increasing the number of go routines.

**Comment by olivere** [comment]
Ah. So I could use the underlying NATS connection for the fire-and-forget case, and the NATS Streaming Server conn for the other? I'll definitely check that. Sorry, I seem to be a bit confused about the mix of NATS and NATS Streaming Server. Are there any plans to merge the two once NATS Streaming Server is stable and going for 1.0?

As for the issue with the goroutines, I will have another look at what's really going on. If I find something that looks like a problem with NATS Streaming Server, I will come back here.

Thanks a lot for your time and effort.

**Comment by kozlovic** [comment]
The reason you can't mix and match is that NATS Streaming uses NATS for communication. Streaming server and clients are not directly connected, they go through the NATS server. So subjects space is isolated with some unique ID. For instance, if in Streaming you are publishing on `foo`, the streaming server listens on say: `_STAN.pub.Xqj9tf4MUfadLp6xPp7vRg.>` and the streaming client will publish on `_STAN.pub.Xqj9tf4MUfadLp6xPp7vRg.foo`. Streaming clients send NATS message that are protocol buffers containing some meta data and the actual payload.

There is no plan to merge NATS and NATS Streaming.
