### ISSUE TITLE
Question regarding subscription callback

### ISSUE THREAD

**Issue by sachinwalia2k8** [nats-io/go-nats-streaming#137]
I am wondering if internally subscription callback work on some worker pool kind of architecture. If yes does it impact anyway when it comes to durable subscriptions? If not is it up to calling code to spawn message consumption in a separate go routine?

**Comment by kozlovic** [comment]
A subscription callback is invoked from an internal go-routine. Messages from that subscription are serialized. That is, the go routine invokes the callback with a message, when callback returns, picks the next message and invokes the callback etc..
You don't have to use a go routine to do message processing, unless you want to. If you do spawn a go routine for each incoming message, note that you will probably process those messages out-of-order.
