### ISSUE TITLE
Usage for stan-bench is incorrect

### ISSUE THREAD

**Issue by rberlind** [nats-io/go-nats-streaming#140]
The usage for stan-bench (https://github.com/nats-io/go-nats-streaming/blob/master/examples/stan-bench.go) is incorrect since it currently refers to "nats-bench" when it should be referring to "stan-bench".   Since the usage for stan-bench has some different options from the nats-bench usage, I suspect that this is the only issue with the usage output.  But someone who knows the code better should check.

**Comment by tylertreat** [comment]
Fixed in #141.
