### ISSUE TITLE
stan: connect request timeout

### ISSUE THREAD

**Issue by bobbytables** [nats-io/go-nats-streaming#142]
Hello,

I'm working on a project that was using the plain ol' `go-nats` package, but I wanted some of the streaming functionality provided by this package so I'm in the process of switching it around.

I'm running into the error `stan: connect request timeout` and I can't seem to figure out why this is occurring. I'm setting a connection to the `stan.Conn` using the `Option` helper like so:

```
// nConn is assigned to a successfully connected *nats.Conn struct
stanConn, err := stan.Connect("consumer", "consumer",
		stan.NatsConn(nConn),
		stan.ConnectWait(time.Second*10),
	)
```

However this is giving the error listed in the title.

I've isolated it to this line in the `go-nats` package: https://github.com/nats-io/go-nats/blob/master/nats.go#L2085

Any thoughts on what might be causing this? I was using the `go-nats` package just fine, publishing and subscribing messages with no hiccups.

**Comment by bobbytables** [comment]
Upon a little further investigation, it looks like the subscription for the discovery is never actually created:

From my NATS Streaming Logs:
```
nats_1         | [1] 2017/06/21 18:05:55.821038 [TRC] 172.26.0.11:56340 - cid:18 - ->> [PING]
nats_1         | [1] 2017/06/21 18:05:55.821185 [TRC] 172.26.0.11:56340 - cid:18 - <<- [PONG]
nats_1         | [1] 2017/06/21 18:05:55.832897 [TRC] 172.26.0.11:56340 - cid:18 - ->> [SUB _INBOX.HeUQZcV1yNagO69yKp4vSB  1]
nats_1         | [1] 2017/06/21 18:05:55.836561 [TRC] 172.26.0.11:56340 - cid:18 - ->> [SUB _INBOX.HeUQZcV1yNagO69yKp4vWv.*  2]
nats_1         | [1] 2017/06/21 18:05:55.836666 [TRC] 172.26.0.11:56340 - cid:18 - ->> [PUB _STAN.discover.accounts-consumer _INBOX.HeUQZcV1yNagO69yKp4vWv.HeUQZcV1yNagO69yKp4vbf 50]
nats_1         | [1] 2017/06/21 18:05:55.836675 [TRC] 172.26.0.11:56340 - cid:18 - ->> MSG_PAYLOAD: [
nats_1         | accounts-consumer_INBOX.HeUQZcV1yNagO69yKp4vSB]
```

**Comment by tylertreat** [comment]
go-nats-streaming isn't a drop-in replacement for go-nats, it's a client library for the [NATS Streaming server](https://github.com/nats-io/nats-streaming-server). Are you actually running this server and not gnatsd?

**Comment by bobbytables** [comment]
Yup, I am running nats streaming. I noticed that I had a discrepancy between the cluster ID between my client and the servers name. So I'm going to close this.
