### ISSUE TITLE
Reconnection on restart and fail-over

### ISSUE THREAD

**Issue by ikaros** [nats-io/go-nats-streaming#153]
Hi 🙂 

I'd like to ask about the intended way of the client to deal with connection losses / fail-overs / reconnects.

I would expect a message which is sent after the nats-streaming-server restarted to be successfully received by a subscriber which subscribed before the restart.

When I do the following I would expect a second message to be received by the subscriber:
1. Start nats streaming: `docker run --name="srv" -d -p 4222:4222 nats-streaming:0.5.0 `
2. Subscribe to "test" channel: `stan-sub -s nats://localhost:4222 -id="c1" test &`
3. Publish first message: `stan-pub -s nats://localhost:4222 test "one"`
4. Restart nats-streaming server: `docker restart srv`
5. Publish second message: `stan-pub -s nats://localhost:4222 test "two"`

`stan-sub` seems to only receive the first message.

Shouldn't the nats-streaming-client take care of reconnection to successfully receive the second message also?

Disclaimer: I'm aware that `stan-pub` and `stan-sub` only example cli tools and I use them only for this example ;-)

**Comment by aricart** [comment]
@ikaros the issue here is that you are starting a nats-streaming-server with a memory store. When you restart the streaming server, the server doesn't have any state for client 'c1'. 

Start your server like this instead:
`docker run -d -p 4222:4222 nats-streaming -st FILE --dir /tmp`

**Comment by ikaros** [comment]
That sounds right.

Thank you 👍

**Comment by aricart** [comment]
Glad it helped. Closing this issue, let me know if you have other questions or doubts.

**Comment by iRatkin** [comment]
Thanks for issue, it works! :)
