### ISSUE TITLE
Connect error if domain used in address.

### ISSUE THREAD

**Issue by rafw** [nats-io/go-nats-streaming#154]
In remote VPS, I run nats-streaming-server v0.6.0 like this.
`nohup nats-streaming-server -m 8222 -p 4222 -DV >/dev/null 2>&1 &`

http://MYDOMAIN:8222 works well. But can't connect it, print "nats: no servers available for connection" all the time.

I tried go client v0.3.4 & newest version both.
`
    _, err := stan.Connect("test-cluster", "myID2", stan.NatsURL("nats://MYDOMAIN:4222"), 
    stan.ConnectWait(time.Second * 10))
	    if err != nil {
		fmt.Println(err)
		return
	}`

After using IP instead, works again.

**Comment by kozlovic** [comment]
Are you checking the monitoring port from the same machine than where you try to connect? Do you get the NATS monitoring page when you go to `http://MYDOMAIN:8222`?

If `MYDOMAIN` resolves correctly on the machine where you create the connection, there is no reason it would fail. Check name resolution on that machine. The fact that when you use the IP it works indicate that this is not a server configuration port mismatch with your client (in the original report you had used the wrong port, but I see that you have fixed the test description now) or the server not reachable. So to me it looks like `MYDOMAIN` does not resolve on that machine.

**Comment by kozlovic** [comment]
Hope you have resolved your issue. I will close this for now, and will re-open if needed. Thanks!
