### ISSUE TITLE
conn.NatsConn.IsConnected returns wrong.

### ISSUE THREAD

**Issue by rafw** [nats-io/go-nats-streaming#156]
After cutting the internet connection of computer. IsConnected() still returns true all the time!

**Comment by kozlovic** [comment]
By default, NATS connection tries to reconnect when it detects that it got disconnected from the server. 

First, when disconnecting the cable, TCP does get notified of an error. This is why most messaging libraries use server-to-client and client-to-server PINGs to detect these kind of failures. NATS is no different. There is a ping interval at which the library sends PINGs and expect to receive  PONGs. After missing a configurable number of PONGs, the library will consider the connection dead and try to reconnect.

By default, NATS library will try to reconnect. Until it does so, IsConnected() will still return true. Only when the number of reconnect attempts would be over that the connection will be terminally closed, in which case IsConnected() should return false.

**Comment by kozlovic** [comment]
Closing for now. We will re-open if you have additional questions/comments. Thanks!
