### ISSUE TITLE
default managed NATS connection is unsuitable for long term use

### ISSUE THREAD

**Issue by ripienaar** [nats-io/go-nats-streaming#174]
By default the NATS connection that gets made does not set any options:

https://github.com/nats-io/go-nats-streaming/blob/1662e177fdb0b7964a25e8e7e3570dd49b763c9a/stan.go#L195

This means defaults will apply such as maximum 60 reconnect attempts and default reconnect time.

Should the connection between the client and NATS broker fail and stay down for a few minutes - long enough for 60 connection attempts - no further reconnects will be attempts and if all your client is doing is consuming messages from the stream - you will never know this have happened.  You'll simply stop receiving messages.

To me this appears to make the transparently managed NATS connection behaviour useless as you'll always have to pass in a pre-made nats connection that has appropriate reconnect settings.

In general I think the internals of this library is way too opaque, we need access to the NATS error callbacks etc, also something you cannot do with the embedded NATS connection

**Comment by ripienaar** [comment]
I think this is even worse than I anticipated above, even if I supply a NATS connection that reconnects forever and I have callback logging so I know it gets connected - if the connection is off long enough, perhaps that the server will disconnect the client due to heartbeats - a long running stan client will never resume, you'll simply never get messages again.

As per https://github.com/nats-io/go-nats-streaming/issues/175 we either need automagical reconnects or a timeout callback should be called

**Comment by kozlovic** [comment]
Having the API simple when you don't need extra configuration I think is a plus, no? You are right that if you want some tuning of the underlying NATS connection you end-up having to create, configure and then pass it to the `stan.Connect()` call. But what would be the alternative, short of duplicating *all* configuration setters?

**Comment by ripienaar** [comment]
@kozlovic agree, the flexibility to pass own connector helps - however by default what you do should at least be functional.  As it stands it is not.

 * max reconnects is default ie. 60 iirc
 * when it reaches max it just stops working forever.

**Comment by kozlovic** [comment]
For your second comment, yes, it is possible that the server did purge the connection before the underlying NATS connection reconnects, in which case the server would reject any new published message from this unknown client (or worse, another app with same client ID may have been started and server would accept messages from 2 apps with same client ID..).

**Comment by kozlovic** [comment]
All valid points that need to be addressed for sure.

**Comment by kozlovic** [comment]
@ripienaar The server change: https://github.com/nats-io/nats-streaming-server/pull/553 should help to reduce or eliminate duplicate redeliveries as you have observed in some cases.
