### ISSUE TITLE
Releasing a new tag

### ISSUE THREAD

**Issue by alexcetto** [nats-io/go-nats-streaming#186]
I would want to know why this library has not been tagged for two years now and if you could plan to release one. 
- This would clarify the state of the code. 
- It will also help programmers managing the versions of dependancies in a clearer way.

**Comment by kozlovic** [comment]
Yes, this is long overdue. There is a PR that I would like to be merged before we issue a new release. We will do so probably in a week or so. Thank you for your patience!

**Comment by kozlovic** [comment]
Done: https://github.com/nats-io/go-nats-streaming/releases/tag/v0.4.0
Thanks!

**Comment by alexcetto** [comment]
Perfect. And thanks for this library! Hope I can contribute in the future.
