### ISSUE TITLE
nats streaming connect fail with "connect request timeout"?

### ISSUE THREAD

**Issue by Aavon** [nats-io/go-nats-streaming#192]
My test code.

```
nc,err := gnats.Connect("nats://<<user>>:<<pass>>@server:4322,...")
	if err != nil {
		log.Fatalln("c1",err)
	}
	err = nc.Publish("foo",[]byte("bar"))
	if err != nil {
		log.Fatalln("foo",err)
	}
	sc, err := stan.Connect("nats-cluster", "stan-pub",stan.NatsConn(nc))
	if err != nil {
		log.Fatalln("c2",err)
	}
```

output.

```
c2 stan: connect request timeout
```

It seems that the stan client can not get the cluster info to set the "PING-PONG" check.

One of my config(others are almost the same).

```
###### NATS specific configuration

port: 4322
monitor_port: 4323

authorization {
  users = [
    {user: XXX,password: XXX}
  ]
  timeout:  1
}

cluster {
  port: 4324

  authorization {
    user: XXX
    password: XXX
    timeout: 0.75
  }
  routes: [
    "nats://XXX:XXX@stan-2:4334",
    "nats://XXX:XXX@stan-3:4344"
  ]
}

# NATS Streaming specific configuration
streaming {
  id: nats-cluster
  store: file
  dir: store
  cluster {
    node_id: "stan-1"
    peers: ["stan-2", "stan-3"]
  }
}
```

Version.

```
images: nats-streaming:0.10.2
go-nats: 1.5.0
go-nats-streaming:0.4.0
```

Are there ang cluster issue, even if the nats cluster works? (We use nats client and streaming client)

**Attached**

the trace log

```
7/12/2018 5:37:39 PM[1] 2018/07/12 09:37:39.593510 [TRC] 10.42.21.225:48470 - rid:11 - ->> [UNSUB RSID:7:1006]
7/12/2018 5:37:39 PM[1] 2018/07/12 09:37:39.593526 [TRC] 10.42.21.225:48470 - rid:11 - <-> [DELSUB RSID:7:1006]
7/12/2018 5:37:39 PM[1] 2018/07/12 09:37:39.593557 [TRC] 10.42.21.225:48470 - rid:11 - ->> [UNSUB RSID:7:1007]
7/12/2018 5:37:39 PM[1] 2018/07/12 09:37:39.593568 [TRC] 10.42.21.225:48470 - rid:11 - <-> [DELSUB RSID:7:1007]
7/12/2018 5:37:40 PM[1] 2018/07/12 09:37:40.063069 [TRC] 10.42.21.225:48470 - rid:11 - ->> [SUB raft.nats-cluster.stan-2.nats-cluster.request._INBOX.mcPn463J1VSqwIhqsLkCee  RSID:7:1010]
7/12/2018 5:37:40 PM[1] 2018/07/12 09:37:40.063105 [TRC] 10.42.21.225:48470 - rid:11 - ->> [SUB raft.nats-cluster.stan-2.nats-cluster.request._INBOX.mcPn463J1VSqwIhqsLkCft  RSID:7:1011]
7/12/2018 5:37:40 PM[1] 2018/07/12 09:37:40.712308 [TRC] 10.42.21.225:48470 - rid:11 - ->> [UNSUB RSID:7:1008]
7/12/2018 5:37:40 PM[1] 2018/07/12 09:37:40.712320 [TRC] 10.42.21.225:48470 - rid:11 - <-> [DELSUB RSID:7:1008]
7/12/2018 5:37:40 PM[1] 2018/07/12 09:37:40.712334 [TRC] 10.42.21.225:48470 - rid:11 - ->> [UNSUB RSID:7:1009]
7/12/2018 5:37:40 PM[1] 2018/07/12 09:37:40.712350 [TRC] 10.42.21.225:48470 - rid:11 - <-> [DELSUB RSID:7:1009]
7/12/2018 5:37:41 PM[1] 2018/07/12 09:37:41.287556 [TRC] 10.42.21.225:48470 - rid:11 - ->> [SUB raft.nats-cluster.stan-2.nats-cluster.request._INBOX.mcPn463J1VSqwIhqsLkCjc  RSID:7:1012]
7/12/2018 5:37:41 PM[1] 2018/07/12 09:37:41.287599 [TRC] 10.42.21.225:48470 - rid:11 - ->> [SUB raft.nats-cluster.stan-2.nats-cluster.request._INBOX.mcPn463J1VSqwIhqsLkCkr  RSID:7:1013]
```

**Comment by kozlovic** [comment]
From your config, I don't see any debug tracing, yet, you provide log with tracing, so not sure if those are related.

Are you sure your NATS Streaming Cluster has formed? Do you see something similar to this in one of the logs?
```
[INF] STREAM: server became leader, performing leader promotion actions
[INF] STREAM: finished leader promotion actions
```
The configuration file that you show here means that each server embeds its own NATS Server. You are configuring the NATS core cluster with the top-level `cluster` section. The streaming specific configuration is in the `streaming` section. I assume that you do not have a separate NATS Servers cluster running, right? (it causes often confusion how NATS server cluster and NATS Streaming cluster interact/differ).

**Comment by Aavon** [comment]
Ooh,Thanks,That's my fault.
I read the section [relate-to-nats](https://github.com/nats-io/nats-streaming-server#relation-to-nats),and understand what confused me.And now the streaming work fine.


>embeded nats cluster: the nats cluster built with the embeded nats server  

1. I used -D -V to get trace log.
2.According to my previous configuration，the nats cluster is formed,but the streaming cluster connect to their embedded nats server(**not the nats cluster**).It cause the "timeout" error(Maybe the streaming  server can not communicate with my client ,like the heartbeat...)
3.One of my new configurates is below,it use a existing nats cluster.

```
# NATS Streaming specific configuration
streaming {
  id: nats-cluster
  store: file
  dir: store
  nats_server_url: "<<nats-cluster-addrs>>"
  cluster {
    node_id: "stan-1"
    peers: ["stan-2", "stan-3"]
  }
}
```

Finally,some advice...

My first configuration is according to [clustering](https://github.com/nats-io/nats-streaming-server#clustering)--"cluster of 3 nodes example".I think it is a little confusing,which leads people to build the embeded nats cluster but the streaming cluster connect to their own embeded nats server(like this issue).And I tried to use embeded nats cluster,it seems not to work,because the streaming connect to cluster befored the embeded nats cluster formed.

Feel free to take it,maybe only I will encounter such a problem，haah

**Comment by kozlovic** [comment]
@Aavon Thank you for the feedback. I have PR https://github.com/nats-io/nats-streaming-server/pull/628 to try clarify the situation. Would you mind having a look and see if that would have prevented your issue? Thanks.

**Comment by kozlovic** [comment]
@Aavon Thanks for the feedback. If I understand you correctly, you are saying that the above is enough and I don't need to list the config (with nats_server_url) for the 3 hosts, is that right?

**Comment by Aavon** [comment]
Yes,haha
