### ISSUE TITLE
stan client does not reconnect?

### ISSUE THREAD

**Issue by huangjunwen** [nats-io/go-nats-streaming#193]
I've created client like this:

``` golang
nc, err := nats.Connect(nats.DefaultURL, nats.MaxReconnects(-1))
// ...
sc, err := stan.Connect("my_cluster", "testsc", stan.NatsConn(nc))
```

Then I use `sc` to publish messages. After a while i stop and restart the streaming server. What i've expected is the messages will continue to be sent. But instead i always got 

```
stan: connection closed
```

P.S. It seems that `sc.nc` become `nil` after the streaming server is stopped.

**Comment by kozlovic** [comment]
If you are using the latest client library with server `0.10.0+`, then there is a feature where client sends PINGs to server. If the disconnect from NATS Streaming server was longer than the number of max pings out, then the library will close the connection and invoke the handler (if you have set one). It also now detects the situation where you would have restarted a Streaming server without persistent store 
(mem store).

More details [here](https://github.com/nats-io/go-nats-streaming#connection-status)

Note that there was an issue with `0.10.0` and you should make sure that you use a `0.10.2` server (issue: https://github.com/nats-io/nats-streaming-server/pull/593).

**Comment by huangjunwen** [comment]
Oh, I didn't notice this section in README. THX

**Comment by kozlovic** [comment]
No worries.. it's rather new.

**Comment by alanyeung95** [comment]
Hello, I come across the same issue. The NATS client cannot reconnect to the server after the server is restarted.

As expected, the connection will be closed and in my case, `stan.SetConnectionLostHandler` will be called. In further, error `stan: connection closed` will be return for every message `publish`.

So what makes me curious is, **could the NATS client re-establish the connection after the server is restarted**, given that both client and server know the `cluster name` and `subject/topic`?

Restarting client itself and create a new connection could be a workaround but it will not be an ideal solution in production I guess.

I find this issue https://github.com/nats-io/stan.go/issues/153#issuecomment-339002926 is related but I will only treat file store as my last resort. Any possible way/solution on memory store?

**Comment by kozlovic** [comment]
In memory store, how do you want the library to reconnect for you? Meaning, if we were to reconnect to the last received, and since with mem store there is no state recovered, your app would miss all the new messages up to the point where the new message seq reach the level they were before the restart.
If the library were to recreate the original sub's start options (say deliver all available), then in the case of a persistent store, for non durable subscriptions, the app would receive all messages that it had received in the past.

**Comment by alanyeung95** [comment]
I got the point, thank you for the quick reply.
