### ISSUE TITLE
Unsubscribe from NATS/NATS Streaming with just Subject (without Subscription structure)

### ISSUE THREAD

**Issue by vandkris** [nats-io/go-nats-streaming#204]
Hi, 
Is there a way to unsubscribe from NATS Streaming without the subscription structure returned from Subscribe() and using just the subject ?

Example below shows using subscription structure returned from Subscribe. Is there another way?
sub, err := sc.Subscribe("foo", func(m *Msg) {})
        if err != nil {
                t.Fatalf("Unexpected error on Subscribe, got %v", err)
        }
        defer sub.Unsubscribe()

Thanks!

**Comment by kozlovic** [comment]
No there is not, you need to call Unsubscribe() on the Subscription object.
