### ISSUE TITLE
Returning to back of queue when not acked

### ISSUE THREAD

**Issue by mgouline** [nats-io/go-nats-streaming#214]
Hi there,

This is a question, rather than necessarily an issue, because I'm most likely doing something silly.

Let's say you have a queue subscriber with a durable name and manual acknowledgement mode enabled. Message handler callback only acknowledges messages when no system error was returned from downstream calls.

```go
_, err := conn.QueueSubscribe(
	subject,
	qgroup,
	func(msg *stan.Msg) {
		if err := processMessage(msg); err == nil {
			msg.Ack(); 
		}
	},
	stan.DurableName(durableName),
	stan.SetManualAckMode(),
	stan.AckWait(stanAckWait),
	stan.MaxInflight(stanMaxInFlight),
)
```

As a result, if the number of messages that haven't been acknowledged (because of some downstream error in `processMessage()`) is equal to the 'max inflight' number, they and only they will forever be re-delivered and no subsequent messages will be let through.

Is there any way to configure NATS streaming to return any unacknowledged messages to the **back** of the queue, rather than just 'max inflight' number of places down from the front? 

Desired outcome: if you have 'max inflight' set to 5 and 5 messages are stuck unacknowledged, the sixth message should be delivered after the next attempt to get these five acknowledged.

Thanks in advance for any advice!

**Comment by mgouline** [comment]
@kozlovic Thanks for your response, fixed the `err == nil` logic for anyone reading it in future 🙂 

So sticking with queue subscription approach, are you saying the solution would be to create two or more subscriptions in the same service (for context: the queue is to send messages from one microservice to another) to unblock the stuck messages by relying on them being spread between multiple subscriptions?

**Comment by mgouline** [comment]
@kozlovic I was just confirming that I understood correctly. Thanks for your insight, I'll give it a go!

**Comment by kozlovic** [comment]
Closing for now. Will re-open if you have more questions. Thanks!
