### ISSUE TITLE
Can't connect: nats: no servers available for connection

### ISSUE THREAD

**Issue by cpani** [nats-io/go-nats-streaming#219]
Hi,
I am facing this issue for connecting to Nats Streaming server.
I have my server running

[1] 2019/01/04 10:06:53.790584 [INF] STREAM: Starting nats-streaming-server[test-cluster] version 0.11.2
[1] 2019/01/04 10:06:53.790624 [INF] STREAM: ServerID: xdbAYK8WyPNA0h68NJQaMk
[1] 2019/01/04 10:06:53.790629 [INF] STREAM: Go version: go1.11.1
[1] 2019/01/04 10:06:53.791115 [INF] Starting nats-server version 1.3.0
[1] 2019/01/04 10:06:53.791124 [INF] Git commit [not set]
[1] 2019/01/04 10:06:53.791214 [INF] Starting http monitor on 0.0.0.0:8222
[1] 2019/01/04 10:06:53.791253 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2019/01/04 10:06:53.791260 [INF] Server is ready

When I try to connect from my client I am getting this error

[Fatal]: Can't connect: nats: no servers available for connection.

Any help would be appreciated.

**Comment by cpani** [comment]
Hi Derek,
I am running the streaming server in the same machine in a container. 
I would like to understand what you mean when say appropriate port mapping and network setup?

Thanks for the help!!

**Comment by derekcollison** [comment]
How are you running the container? Is this via Docker or K8S? You need to map the ports we bind to inside the container to be available outside the container.

See Example Usage here - https://hub.docker.com/_/nats

**Comment by cpani** [comment]
Yes, I am running it on docker.
Here is my mappings in docker-compose.yml. Do you see any problem in this?

nats1:
    image: library/nats-streaming
    links:
     - "client-router"

    ports:
        - "4222:4222"

**Comment by derekcollison** [comment]
How do you try to connect from the host to the NATS server? What IP are you using?

**Comment by cpani** [comment]
I am using defaul Nats URL to connect. 
stan.connect(“cluster”, “client”, natsDefaultIRL).

**Comment by derekcollison** [comment]
What does `telnet localhost 4222` show? Running from the same place you try to run the client application.

**Comment by cpani** [comment]
telnet localhost 4222 is giving me following info:
INFO {"server_id":"9w3xpW8TI8ysQ367PADvhT","version":"1.3.0","proto":1,"go":"go1.11.1","host":"0.0.0.0","port":4222,"max_payload":1048576,"client_id":4}

**Comment by cpani** [comment]
@wallyqs Yes, I am running the client from another docker container. Will there be any change , if we run the server and client in two different containers?

**Comment by wallyqs** [comment]
@cpani yes you will likely have to use the name of the docker link to be able to connect to the nats container.  Looking at the example compose shared on the comment above I think you would have to connect like this maybe: 

```go
sc, err := stan.Connect("test-cluster", "client-id" stan.NatsURL("nats://nats1:4222"))`
```
https://docs.docker.com/v17.12/docker-cloud/apps/service-links/#service-link-example
