### ISSUE TITLE
Using cluster name other than test-cluster

### ISSUE THREAD

**Issue by cpani** [nats-io/go-nats-streaming#225]
Hello,

I am facing a issue with cluster name. Whenever I use "test-cluster" for cluster name `stan.Connect("test-cluster", clientID, "nats://localhost:4222")` , I am able to establish the connection. 

But if I give any other name `stan.Connect("abc-cluster", clientID, "nats://localhost:4222")`, I am not able to establish the connection. 

Is there anything wrong  in the above code?

**Comment by wallyqs** [comment]
You need to start the server as well using that cluster-id for it to be able to connect using that name:

```
nats-streaming-server --cluster_id abc-cluster
```
