### ISSUE TITLE
add `Status()` api for stan connection

### ISSUE THREAD

**Issue by shohi** [nats-io/go-nats-streaming#230]
Sometimes it is useful for callers to know which status the stan connection is in, especially when something goes wrong and no callback has been triggered yet.

**Comment by kozlovic** [comment]
@shohi I am not sure there would be value there. A Streaming connection is more of a logical thing than physical. As you may know, there is no direct TCP connection between a streaming client and the streaming server.
A streaming client could have a physical NATS connection to a NATS server and yet not be connected to the Streaming server (I mean even not be a valid streaming client - that is, not registered), and vice-versa, lose the NATS connection but the server would still have this client registered (up to the server-to-client heartbeat timeouts).
You can get the low level NATS connection status from the streaming connection `Conn.NatsConn()`.
For streaming, it would be more of a "on" or "off" (which you get if you setup the connection lost handler)

**Comment by shohi** [comment]
Yeah, i know what you mean. The problem i encounter is some business logic may depend on the status of streaming connection. For example, when nats streaming server is closed and the max ping out of stan connection has not been reached, all the following sub/pub via the connection will be failed, but i don't know whether these operations should be retried.

And also not sure whether there is another possible way to handle this scenario.

**Comment by kozlovic** [comment]
@shohi If the Streaming server were to be shutdown, yes, the PINGs will not get a response and you will have to wait your max ping outs before the connection is reported as closed.
But again, there is no way for the client library to know that operation should not be retried. There is no direct TCP connection, so it could be that there is a network issue between server and client. Stopping at the very first missed ping response would be bad in my opinion.
It also works the other way around, that is, yes the server may be shutdown but then restarted a bit later and your application would still have a "connection" to the server (until the max ping out is reached). So your subscriptions are fine, the publishers are more of a problem if your messages don't include something that makes them idempotent from a subscription perspective (meaning that they can be detected as duplicates or processing of a duplicate message is a no-ope).

**Comment by shohi** [comment]
@kozlovic thanks for your explanation :-). Here is another question about subscriptions. If the server gets restarted and all subscriptions on it are lost (e.g. launched in memory mode),  and max ping out of client connection is not reached yet, is the client connection still valid and no callback will be triggered? if so, what about subscriptions established on this connection? are they recreated?
if not, then the connection can't receive any message from the subjects it's interested in. In this situation, the connection does not work properly IMO.

**Comment by kozlovic** [comment]
@shohi Let's be clear: if your server(s) use memory store, no state is ever recovered so all your client connections will have to be re-created.

You can tune the client-to-server PINGs intervals/max out to make it as "fast" as you want to detect this situation.

Note that for a publisher, after the server is restarted, and even if the library has not detected yet that the connection is invalid, the publish call should fail saying that the client ID is not valid on the server.

The PING is more helpful for subscriptions since the restarted server will have no state, your app will definitively not receive anything on those subs. The library once it detects that the connection is lost will invoke the callback and you will have to recreate connection and subscriptions.

**Comment by kozlovic** [comment]
@shohi Here is some info about the rationale behind the PINGS: https://github.com/nats-io/go-nats-streaming/pull/183 and in the README: https://github.com/nats-io/go-nats-streaming#connection-status

**Comment by shohi** [comment]
@kozlovic The PR description is awesome! It's much clear now about the "connection".  

Duplicated messages are not a big problem as this is in line with the design - at least once delivery. Compare to publishing, I care more about subscriptions on the connection. It may be a problem if we can't receive any notifications if subscriptions have some changes. Could we make such assertion about the subscription -- if subscription gets lost then the registered callback will be called definitely? 

Thank you very much for your patient explanation. What you said makes sense, the `Status` API is not accurate and not useful. I'll close the issue later, perhaps we can expose the `PingOut()` if the caller wants the internal state of the PINGs.

**Comment by kozlovic** [comment]
> Could we make such assertion about the subscription -- if subscription gets lost then the registered callback will be called definitely?

The subscription will not get lost on its own. Instead, if the connection between the client and the server is no longer valid that the subscription would stop receiving messages. But if you set the connection lost handler, then your application will be notified when the connection is considered permanently lost.

Not sure if exposing PingsOut() makes sense (I have let things to be added to this API that I regret now, namely all the low-level NATS subscriptions APIs). What would your application do with the result of PingsOut()? If you don't want to tolerate less than 1 ping out, then set PingsOut to 2 and your application will be notified as soon as it misses more than 1 ping and the connection will be closed. You can then try to recreate everything.
(note that when the library sends a PING, the "number of pings out" increases, so say is 1, and the library receives asynchronously the response, which decrement that number. So if there was a PingsOut() API and you query at the "wrong" time, you may be under the impression that there is an issue, while there actually is not).

**Comment by shohi** [comment]
@kozlovic Subscription lost i mentioned here refers to stan server loses the corresponding record due to somehow. 

As to `PingsOut`, sorry for not considering it deeply.  It has the same problems as `Status` API - inaccurate and misleading.

The main reasons for needing these APIs are that I don't want to recreate connections frequently (which is a little expensive) and to publish and subscribe on "broken" connection until it's back to normal. The "broken" is defined by `Status` or `PingsOut`. But as you've explained, none of these APIs is suitable for this scenario.
