### ISSUE TITLE
Using the protobufs to make a new language client

### ISSUE THREAD

**Issue by gedw99** [nats-io/go-nats-streaming#238]
I am thinking about how hard to would be to gen a new language client from the proto buffers.

Is this repo the best source or is the streaming server protobuffers better ?

I am looking to make a dart client . The current one only supports the non streaming NATS API unfortunately.

I can probably do the NUID and nkeys and jet stuff in dart easily 
So hopefully just need to handle reconnection semantics and maybe a few other semantics ?

Also would love to know if grpc will be the basis for the Jetstream architecture that is slides to for 2019.

**Comment by kozlovic** [comment]
If you write a client, you need to use the protocol that is in this repo, not the one in the server. As to wether we will use protobufs for Jetstream, not entirely sure, but the idea was to do without.
