### ISSUE TITLE
Msg is leaking transport protocol

### ISSUE THREAD

**Issue by JensRantil** [nats-io/go-nats-streaming#246]
https://godoc.org/github.com/nats-io/go-nats-streaming#Msg is inheriting `pb.MsgProto`. This means that usage of the implementation is tied to a transport protocol. IMHO this is a bad long-term design choice as serialization format can change etc. Have you considered making `Msg` an interface? Or at, likely less intrusive, adding functions to `Msg` to access the data (and add a comment that use those instead of accessing low-level protobuf)?

**Comment by kozlovic** [comment]
Be assured that we are not planning on changing MsgProto, at least not remove fields (always possible to add some).
But yes, it probably should not have been exposed like that. But at this point, I think it is a bit too late. Adding functions to get the Sequence, etc.. would not prevent direct access to the embedded MsgProto through Msg.Sequence. Making MsgProto private would break existing applications.

**Comment by JensRantil** [comment]
:+1: Feel free to close this issue if you want.
