### ISSUE TITLE
Document Conn#Close behaviour when using NatsConn(...) Option

### ISSUE THREAD

**Issue by JensRantil** [nats-io/go-nats-streaming#249]
I just spent close to a day debugging why an application I was running was crashing. Turns out it was continuously running out of file descriptors because the NATS connection was not closed [when using NatsConn(...) Option](https://github.com/nats-io/go-nats-streaming/blob/master/stan.go#L292-L308). How about documenting in https://godoc.org/github.com/nats-io/go-nats-streaming#NatsConn that using this `Option` [changes the behaviour of `Conn#Close`](https://github.com/nats-io/go-nats-streaming/blob/master/stan.go#L576)?

**Comment by kozlovic** [comment]
@JensRantil let me know if #250 would address the issue. Thanks!
