### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by JensRantil** [nats-io/go-nats-streaming#251]
I have a small ping application which looks like it is leaking memory. I'm running it in K8s, it dies after a while and this is what the memory curve looks like:

<img width="428" alt="Screenshot 2019-05-02 at 22 55 06" src="https://user-images.githubusercontent.com/730342/57106331-5d6ea900-6d2d-11e9-8b52-c37630f0aab4.png">

I've condensed the application down to https://gist.github.com/JensRantil/b0889cccc0256064a109f8edfd7c9300. Essentially the application connects to STAN/NATS 20k times, then does an explicit GC and sleeps for operator to look at the heap. No subscription nor publish takes place for every connect. I run it like this:
```bash
$ nats-streaming-server &
$ GOGC=5 ./nats-streaming-pinger -cluster test-cluster &
$ # Wait until all messages have been sent and GC executed.
$ wget -qO goroutines http://localhost:6060/debug/pprof/goroutine\?debug\=2
$ wget -q http://localhost:6060/debug/pprof/heap
$ go tool pprof ./heap
Type: inuse_space
Time: May 2, 2019 at 11:01pm (CEST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 838.63MB, 98.07% of 855.13MB total
Dropped 53 nodes (cum <= 4.28MB)
Showing top 10 nodes out of 31
      flat  flat%   sum%        cum   cum%
  656.02MB 76.72% 76.72%   656.02MB 76.72%  bufio.NewWriterSize (inline)
  110.56MB 12.93% 89.65%   110.56MB 12.93%  math/rand.NewSource
   26.03MB  3.04% 92.69%   699.05MB 81.75%  github.com/nats-io/go-nats.Options.Connect
   16.51MB  1.93% 94.62%   852.13MB 99.65%  github.com/nats-io/go-nats-streaming.Connect
      12MB  1.40% 96.02%       16MB  1.87%  github.com/nats-io/go-nats.(*Conn).subscribe
    5.50MB  0.64% 96.67%     5.50MB  0.64%  github.com/nats-io/go-nats-streaming/pb.(*ConnectResponse).Unmarshal
    4.50MB  0.53% 97.19%     4.50MB  0.53%  sync.NewCond (inline)
       4MB  0.47% 97.66%     5.50MB  0.64%  github.com/nats-io/go-nats.(*Conn).addURLToPool
       2MB  0.23% 97.89%   120.07MB 14.04%  github.com/nats-io/go-nats.(*Conn).Request
    1.50MB  0.18% 98.07%        7MB  0.82%  github.com/nats-io/go-nats.(*Conn).setupServerPool
(pprof)
```
I'm defining `GOGC=5` to force Go GC to run a bit more aggresively just in case.

I've ran my application up to 100k connects/closes and it used ~2 GB of memory at that point.

**Expected:** That ~600 MB isn't allocated in inuse_space. Given that I'm simply opening connection and then closing I'd expect memory usage to be around 50 MB or so.

I'm attaching my heap dump here and goroutine listing here: 

[nats-mem-leak.zip](https://github.com/nats-io/go-nats-streaming/files/3139967/nats-mem-leak.zip)

It looks like no NATS goroutines are running. Let me know if you believe I have misunderstood anything.

**Comment by derekcollison** [comment]
Do you close the STAN connections?

**Comment by kozlovic** [comment]
Yes, I look at his test program and he does. Will run that and see if I can reproduce. The issue is with the buffer writer created by the go NATS client. Wonder if we need to set this to nil on Close()?

**Comment by JensRantil** [comment]
FYI, I just pushed my `go.mod` in the gist so you have my exact dependencies.

**Comment by JensRantil** [comment]
> Yes, I look at his test program and he does. Will run that and see if I can reproduce. The issue is with the buffer writer created by the go NATS client. Wonder if we need to set this to nil on Close()?

@kozlovic Did you manage to recreate it?

**Comment by JensRantil** [comment]
Worth pointing out that I have a similar roundtrip checked application which continuously sends a message to NATS/gnatsd (not STAN). It reconnects on every check (and does that twice per second) and it works like a charm (that is, no memory leak AFAIK). That application is using `github.com/nats-io/go-nats v1.7.2`.

**Comment by kozlovic** [comment]
Thanks for all the info. I am going to try to work on this today.

**Comment by kozlovic** [comment]
I can reproduce. Working on this. Thank you very much for the detailed report and test case!

**Comment by kozlovic** [comment]
@JensRantil If you could run some tests with code from PR #252 to verify, that would be great. I have verified that the attached test case and added test in the repo now do not show inuse_space like they use to. Thanks again for the report!

**Comment by JensRantil** [comment]
> @JensRantil If you could run some tests with code from PR #252 to verify, that would be great. I have verified that the attached test case and added test in the repo now do not show inuse_space like they use to. Thanks again for the report!

@kozlovic Sorry for not getting back here. Have been a busy week. Given your test case in the PR I'm pretty sure it fixes the issue. Would it be possible for you to make a release containing this fix?

**Comment by kozlovic** [comment]
@JensRantil Done: https://github.com/nats-io/go-nats-streaming/releases/tag/v0.4.4
