### ISSUE TITLE
Allow Connection Callbacks

### ISSUE THREAD

**Issue by mcqueary** [nats-io/go-nats-streaming#29]
We need to provide a mechanism for users to install async error and connection callbacks, or to preserve/honor already-registered callbacks when passing a NATS connection into a STAN connection (see #27).

One approach we have discussed is to have STAN install its own connection handlers, and to invoke any callbacks the user may have already registered on the NATS connection from the STAN handlers.

This can also be applied if we allow STAN to install connection handlers via the client API, i.e. if the user invokes `sc.setDisconnectedCallback(someCB)`, we could invoke this from within our own STAN-installed callbacks.

**Comment by ColinSullivan1** [comment]
Callbacks can be set on the underlying NATS connection; the NATS streaming library does not add or override them.
